# Generated by Django 4.2.30 on 2026-09-17 15:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region_center', models.CharField(max_length=255)),
                ('region_radius_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contract_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contract_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('guarantee_ceiling', models.DecimalField(decimal_places=2, max_digits=14)),
                ('references_held', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('capabilities_excluded', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('available_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('guarantee_required', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('references_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('distance_from_augsburg_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('guarantee_required', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('references_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('construction_window', models.CharField(blank=True, max_length=255)),
                ('cpv_code', models.CharField(blank=True, max_length=50)),
                ('raw_document_key', models.CharField(blank=True, max_length=500)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-extracted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('HARD_FAIL', 'Hard fail'), ('FLAG', 'Flag'), ('CANDIDATE', 'Candidate')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('source_snippet', models.TextField(blank=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='api.company')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='api.lot')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='api.tender')),
            ],
            options={
                'ordering': ['tender_id', 'lot_id'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.tender'),
        ),
    ]
