# Generated by Django 4.2.30 on 2026-09-17 17:23

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='distance_from_augsburg_km',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='verdict',
            name='source_snippet',
        ),
        migrations.AddField(
            model_name='company',
            name='can_show',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='cannot_show',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verdict',
            name='context',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='verdict',
            name='reason_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
