# Generated by Django 4.2.30 on 2026-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_region_lat_company_region_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='submission_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
