"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import parse_qs, urlparse

from decouple import config as env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fby@c(1a(gh36)%v(jr*8ygpqquai0=_h-pnvm=(h1i%s8hki%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [h for h in env('ALLOWED_HOSTS', default='').split(',') if h]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
INSTALLED_APPS += ['corsheaders', 'ninja', 'storages', 'core', 'api', 'storage_client']       # added for CORS support, API endpoints, and S3 storage

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                                # added for CORS support
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [o for o in env('CORS_ALLOWED_ORIGINS', default='').split(',') if o]  # added for CORS support

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = env('DATABASE_URL', default='')  # Neon's single connection-string form

if DATABASE_URL:
    _db_url = urlparse(DATABASE_URL)
    _db_query = parse_qs(_db_url.query)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_url.path.lstrip('/'),
            'USER': _db_url.username,
            'PASSWORD': _db_url.password,
            'HOST': _db_url.hostname,
            'PORT': _db_url.port or 5432,
            'OPTIONS': {
                'sslmode': _db_query.get('sslmode', [env('DB_SSLMODE', default='require')])[0],
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),   # Neon pooled host, see Section 6
            'PORT': env('DB_PORT', default='5432'),
            'OPTIONS': {'sslmode': env('DB_SSLMODE', default='require')},
        }
    }

# Backblaze B2 (S3-compatible)
AWS_ACCESS_KEY_ID = env('B2_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = env('B2_APPLICATION_KEY', default='')
AWS_STORAGE_BUCKET_NAME = env('B2_BUCKET_NAME', default='')
AWS_S3_ENDPOINT_URL = env('B2_ENDPOINT_URL', default='')
AWS_S3_REGION_NAME = env('B2_REGION_NAME', default='')
AWS_S3_ADDRESSING_STYLE = 'virtual'
# Bucket visibility (public vs private) isn't confirmed, and B2's ACL
# support is stricter than AWS S3's - leave AWS_DEFAULT_ACL unset and
# AWS_QUERYSTRING_AUTH at its default (True), so default_storage.url()
# always returns a working signed URL regardless of bucket visibility.
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
